using Clothes_Shop_ERP.DAL;
using Clothes_Shop_ERP.Localization;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Forms;

namespace Clothes_Shop_ERP
{
    // One product + several colors + several sizes picked here becomes every
    // (color, size) combination as a separate ProductVariants row, generated by
    // UcProductVariants.BulkAddVariants() - this dialog only collects the choices.
    public partial class FrmBulkVariantAdd : DevExpress.XtraEditors.XtraForm
    {
        public int ProductId => _productIds[CmbProduct.SelectedIndex];
        public decimal SalePrice => (decimal)SpinSalePrice.Value;
        public decimal CostPrice => (decimal)SpinCostPrice.Value;

        public List<int> SelectedColorIds
        {
            get
            {
                var ids = new List<int>();
                foreach (CheckedListBoxItem item in CklColors.CheckedItems)
                    ids.Add((int)item.Value);
                return ids;
            }
        }

        public List<int> SelectedSizeIds
        {
            get
            {
                var ids = new List<int>();
                foreach (CheckedListBoxItem item in CklSizes.CheckedItems)
                    ids.Add((int)item.Value);
                return ids;
            }
        }

        private ComboBoxEdit CmbProduct;
        private CheckedListBoxControl CklColors, CklSizes;
        private SpinEdit SpinSalePrice, SpinCostPrice;
        private List<int> _productIds = new List<int>();

        public FrmBulkVariantAdd(string title)
        {
            this.Text = title;
            this.Width = 480;
            this.Height = 500;
            this.StartPosition = FormStartPosition.CenterParent;
            this.FormBorderStyle = FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;

            var lblProduct = new LabelControl { Text = LocalizationManager.T("FrmVariantEdit_Product"), Location = new System.Drawing.Point(20, 20) };
            CmbProduct = new ComboBoxEdit { Location = new System.Drawing.Point(20, 40), Width = 420 };
            CmbProduct.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;

            var lblColors = new LabelControl { Text = LocalizationManager.T("BulkVariant_Colors"), Location = new System.Drawing.Point(20, 75) };
            CklColors = new CheckedListBoxControl { Location = new System.Drawing.Point(20, 95), Width = 200, Height = 180 };

            var lblSizes = new LabelControl { Text = LocalizationManager.T("BulkVariant_Sizes"), Location = new System.Drawing.Point(240, 75) };
            CklSizes = new CheckedListBoxControl { Location = new System.Drawing.Point(240, 95), Width = 200, Height = 180 };

            var lblSalePrice = new LabelControl { Text = LocalizationManager.T("FrmVariantEdit_SalePrice"), Location = new System.Drawing.Point(20, 290) };
            SpinSalePrice = new SpinEdit { Location = new System.Drawing.Point(20, 310), Width = 200 };
            SpinSalePrice.Properties.MaxValue = 999999;
            SpinSalePrice.Properties.DisplayFormat.FormatString = "n2";

            var lblCostPrice = new LabelControl { Text = LocalizationManager.T("FrmVariantEdit_CostPrice"), Location = new System.Drawing.Point(240, 290) };
            SpinCostPrice = new SpinEdit { Location = new System.Drawing.Point(240, 310), Width = 200 };
            SpinCostPrice.Properties.MaxValue = 999999;
            SpinCostPrice.Properties.DisplayFormat.FormatString = "n2";

            using (var db = new ClothesShopDBContext())
            {
                foreach (var p in db.Products
                    .Include(x => x.Category)
                    .Where(x => x.IsActive == true && x.Category.IsActive == true)
                    .ToList())
                {
                    CmbProduct.Properties.Items.Add($"{p.Code} - {p.Name}");
                    _productIds.Add(p.Id);
                }
                foreach (var c in db.Colors.ToList())
                    CklColors.Items.Add(new CheckedListBoxItem(c.Id, c.Name));
                foreach (var sz in db.Sizes.OrderBy(x => x.SortOrder).ToList())
                    CklSizes.Items.Add(new CheckedListBoxItem(sz.Id, sz.Name));
            }

            if (_productIds.Count > 0)
            {
                CmbProduct.SelectedIndex = 0;
                using (var db = new ClothesShopDBContext())
                {
                    var basePrice = db.Products.Where(p => p.Id == _productIds[0]).Select(p => p.BasePrice).FirstOrDefault();
                    SpinSalePrice.Value = basePrice;
                }
            }

            // Same convenience as the single-variant dialog (FrmVariantEdit) -
            // switching the product re-suggests that product's own base price.
            CmbProduct.SelectedIndexChanged += (s, e) =>
            {
                if (CmbProduct.SelectedIndex < 0) return;
                using (var db = new ClothesShopDBContext())
                {
                    int productId = _productIds[CmbProduct.SelectedIndex];
                    var basePrice = db.Products.Where(p => p.Id == productId).Select(p => p.BasePrice).FirstOrDefault();
                    SpinSalePrice.Value = basePrice;
                }
            };

            var btnSave = new SimpleButton { Text = LocalizationManager.T("Shared_BtnSave"), Location = new System.Drawing.Point(220, 420), Width = 100, DialogResult = DialogResult.OK };
            btnSave.Click += (s, e) =>
            {
                if (CmbProduct.SelectedIndex < 0 || SelectedColorIds.Count == 0 || SelectedSizeIds.Count == 0)
                {
                    XtraMessageBox.Show(LocalizationManager.T("BulkVariant_MustSelectAll"));
                    this.DialogResult = DialogResult.None;
                }
            };

            var btnCancel = new SimpleButton { Text = LocalizationManager.T("Shared_BtnCancel"), Location = new System.Drawing.Point(330, 420), Width = 100, DialogResult = DialogResult.Cancel };

            this.Controls.Add(lblProduct); this.Controls.Add(CmbProduct);
            this.Controls.Add(lblColors); this.Controls.Add(CklColors);
            this.Controls.Add(lblSizes); this.Controls.Add(CklSizes);
            this.Controls.Add(lblSalePrice); this.Controls.Add(SpinSalePrice);
            this.Controls.Add(lblCostPrice); this.Controls.Add(SpinCostPrice);
            this.Controls.Add(btnSave); this.Controls.Add(btnCancel);

            this.AcceptButton = btnSave;
            this.CancelButton = btnCancel;
        }
    }
}
